version: "3.9"

volumes:
  pgdata_volume:
  logs_volume_bot:
  logs_volume_smr:

networks:
  smr_bot:
    driver: bridge

services:

  postgres_ru:
    build:
      context: .
      dockerfile: Database/Dockerfile
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: always
    volumes:
      - pgdata_volume:/var/lib/postgresql/data
    networks:
      - smr_bot
    env_file:
      - .env

  bot:
    build:
      context: .
      dockerfile: Bot/Dockerfile
    restart: always
    volumes:
      - logs_volume_bot:/Logs
    env_file:
      - .env
    networks:
      - smr_bot
    depends_on:
      - postgres_ru

  meter_sender:
    build:
      context: .
      dockerfile: MeterSender/Dockerfile
    restart: always
    volumes:
      - logs_volume_smr:/Logs
    env_file:
      - .env
    networks:
      - smr_bot
    depends_on:
      - postgres_ru
