version: "3"

volumes:
  BD_SQLite_volume:
  Logs_volume:

services:
  smr-bot:
    build: Bot/
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - BD_SQLite_volume:/Database
      - Logs_volume:/Logs

  smr-meter_sender:
    build: MeterSender/
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - BD_SQLite_volume:/Database
      - Logs_volume:/Logs