version: "3"

volumes:
  pgdata_volume:
  Logs_volume:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=smr
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=smr
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - pgdata_volume:/var/lib/postgresql/data

  smr-bot:
    build: Bot/
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - Logs_volume:/Logs

  smr-meter_sender:
    build: MeterSender/
    restart: always
    environment:
      - TZ=Europe/Moscow
    volumes:
      - Logs_volume:/Logs
